tunnel: <replace_with_tunnel_uuid>
credentials-file: /etc/cloudflared/<replace_with_tunnel_uuid>.json

ingress:
  - hostname: chat.grupototum.com
    service: http://127.0.0.1:3210
  - service: http_status:404
